/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafico;

import Conexiones.Facade;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author vicen
 */
public class Modificar1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Eliminar
     */
    public Modificar1() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        m.moficarTabla(tableDatos,modelo);
        m.actualizarTabla(tableDatos, modelo);
      
    }
    
     DefaultTableModel modelo=new DefaultTableModel() ;
     private TableRowSorter trsfiltro;
     Facade fachada=new Facade();
     MetodosExtra m=new MetodosExtra();
     iconoMensaje m2=new iconoMensaje();
     
     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jCB = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtF1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA1 = new javax.swing.JTextArea();

        setClosable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(539, 484));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Seleccione La Encuesta A Modificar:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Buscar Por:");

        txtFBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFBuscarKeyTyped(evt);
            }
        });

        tableDatos = new javax.swing.JTable(){
            public boolean isCellEditable (int row, int column) {
                return false;
            }
        };
        tableDatos.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        tableDatos.getTableHeader().setResizingAllowed(false);
        tableDatos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableDatos);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(255, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setPreferredSize(new java.awt.Dimension(79, 23));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jCB.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOMBRE", "ID" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Descripcion:");

        txtA1.setColumns(20);
        txtA1.setRows(5);
        jScrollPane2.setViewportView(txtA1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(txtF1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(58, 58, 58)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(txtF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed

      
          m.limpiarTabla(tableDatos, modelo);
          Object[][] datoss=m.obtenerMatrizDatos();
          int i=0;
          for(Object d:datoss){
          modelo.addRow(datoss[i]);
          i++; }
      
         // tableDatos.setModel(modelo); no es necesario
     
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed


int filaseleccionada=tableDatos.getSelectedRow();//obtengo fila
int f1=-1;
try{
 f1=(int) tableDatos.getValueAt(filaseleccionada,0);// columna 0 es id
}catch(Exception ex){

}

String nombre=txtF1.getText();
String descripcion=txtA1.getText();

String textoDesc=descripcion.replaceAll(" ", "");
String textoNombre=nombre.replaceAll(" ", "");

if(f1!=-1){
if(textoDesc.length()!=0  && textoNombre.length()!=0){

fachada.modificarNombre(f1,nombre);
fachada.modificarInstrucciones(f1, descripcion);

m2.setEleccion(1);
JOptionPane.showMessageDialog(null, "SE HA MODIFICADO", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE,m2);
m.actualizarTabla(tableDatos, modelo);

}else{

if(textoNombre.length()>0){

fachada.modificarNombre(f1, nombre);
m2.setEleccion(1);
JOptionPane.showMessageDialog(null, "SE HA MODIFICADO", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE,m2);
m.actualizarTabla(tableDatos, modelo);

}
if(textoDesc.length()>0){

fachada.modificarInstrucciones(f1, descripcion);
m2.setEleccion(1);
JOptionPane.showMessageDialog(null, "SE HA MODIFICADO", "CONFIRMACION", JOptionPane.INFORMATION_MESSAGE,m2);
m.actualizarTabla(tableDatos, modelo);

}
if(textoNombre.length()==0 && textoDesc.length()==0 ){
m2.setEleccion(0);
JOptionPane.showMessageDialog(null, "NO SE HA MODIFICADO", "DENEGADO", JOptionPane.INFORMATION_MESSAGE,m2);
m.actualizarTabla(tableDatos, modelo);

}}

}else{

} 


//fachada.modificarNombre(f1, descripcion);
//fachada.modificarInstrucciones(f1, descripcion);






      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtFBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFBuscarKeyTyped


        
txtFBuscar.addKeyListener(new KeyAdapter() {
public void keyReleased(final KeyEvent e) {
//String cadena = (txtFBuscar.getText()).toUpperCase();
//txtFBuscar.setText(cadena);
//repaint();
m.filtro(txtFBuscar,trsfiltro,m.obtnerCombo(jCB));
}
});
trsfiltro = new TableRowSorter(tableDatos.getModel());
tableDatos.setRowSorter(trsfiltro);



        // TODO add your handling code here:
    }//GEN-LAST:event_txtFBuscarKeyTyped
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableDatos;
    private javax.swing.JTextArea txtA1;
    private javax.swing.JTextField txtF1;
    private javax.swing.JTextField txtFBuscar;
    // End of variables declaration//GEN-END:variables
}
